//go:build goexperiment.simd && arm64 && go1.27

package tensai

// The register tiles of the dense float product, in assembly
// (dot_tile_arm64.s, generated by gen_tile_arm64.py). tileRx16 adds
// a[0:R, 0:k] * b[0:k, 0:16] into the R x 16 block of out at o -- or
// writes it there when load is 0 -- where o, a and b point at the block's
// first element and ldo, lda and ldb are the three matrices' row strides
// in elements.
//
// Each step multiplies one row of b by an element of a with FMLA (by
// element), which reads the element straight from a lane of a vector
// register. The Go kernel had to broadcast it first, three vector
// instructions per element of a: on the four-row tile that was 12 vector
// instructions beside the 16 multiply-adds, all on the same pipes, plus
// the bounds checks of each step. The sums are the same fused
// multiply-adds in the same k order, so the results are bit for bit those
// of the Go tile and of dotRowsAxpy, with the exceptions dotRowsTiled
// names.

//go:noescape
func tile4x16(o, a, b *float32, ldo, lda, ldb, k, load uintptr)

//go:noescape
func tile3x16(o, a, b *float32, ldo, lda, ldb, k, load uintptr)

//go:noescape
func tile2x16(o, a, b *float32, ldo, lda, ldb, k, load uintptr)

//go:noescape
func tile1x16(o, a, b *float32, ldo, lda, ldb, k, load uintptr)
