#!/usr/bin/env python3
# Generates dot_tile_arm64.s: the R x 16 register tiles (R = 1..4) of out = a * b
# with by-element FMLA (dot_tile_arm64.go). Run: python3 gen_tile_arm64.py > dot_tile_arm64.s
import sys

def fmla_elem(d, n, m, idx):
    # FMLA Vd.4S, Vn.4S, Vm.S[idx]  (single precision, by element; Vm in V0..V31)
    assert 0 <= m < 32 and 0 <= idx < 4
    L, H = idx & 1, idx >> 1
    M, rm = m >> 4, m & 15
    return 0x4F801000 | (L << 21) | (M << 20) | (rm << 16) | (H << 11) | (n << 5) | d

out = []
w = out.append
w("// Code generated by gen_tile_arm64.py; DO NOT EDIT.")
w("")
w("//go:build goexperiment.simd && arm64 && go1.27")
w("")
w('#include "textflag.h"')
w("")
for R in (4, 3, 2, 1):
    acc = lambda r, c: 4 * r + c          # V0..V15
    av = lambda r: 16 + r                 # V16..V19: four k values of a's row r
    bv = lambda c: 20 + c                 # V20..V23: one row of b, 16 wide
    w(f"// func tile{R}x16(o, a, b *float32, ldo, lda, ldb, k, load uintptr)")
    w(f"TEXT ·tile{R}x16(SB), NOSPLIT, $0-64")
    w("\tMOVD o+0(FP), R0")
    w("\tMOVD a+8(FP), R1")
    w("\tMOVD b+16(FP), R2")
    w("\tMOVD ldo+24(FP), R3")
    w("\tMOVD lda+32(FP), R4")
    w("\tMOVD ldb+40(FP), R5")
    w("\tMOVD k+48(FP), R6")
    w("\tMOVD load+56(FP), R7")
    w("\tLSL $2, R3, R3")   # strides in bytes
    w("\tLSL $2, R4, R4")
    w("\tLSL $2, R5, R5")
    # row pointers of a: R8..R11; rows of out: R12..R15 (R13 ok on arm64 Go? avoid R18 platform, R28 g, R29 FP, R30 LR, R27 tmp)
    rowa = ["R8", "R9", "R10", "R11"]
    rowo = ["R12", "R13", "R14", "R15"]
    w("\tMOVD R1, R8")
    w("\tMOVD R0, R12")
    for r in range(1, R):
        w(f"\tADD R4, {rowa[r-1]}, {rowa[r]}")
        w(f"\tADD R3, {rowo[r-1]}, {rowo[r]}")
    # accumulators: zero or load
    w("\tCBZ R7, zero%d" % R)
    for r in range(R):
        w(f"\tVLD1 ({rowo[r]}), [V{acc(r,0)}.S4, V{acc(r,1)}.S4, V{acc(r,2)}.S4, V{acc(r,3)}.S4]")
    w(f"\tB loop4start{R}")
    w(f"zero{R}:")
    for r in range(R):
        for c in range(4):
            v = acc(r, c)
            w(f"\tVEOR V{v}.B16, V{v}.B16, V{v}.B16")
    w(f"loop4start{R}:")
    w("\tCMP $4, R6")
    w(f"\tBLT tail{R}")
    w(f"loop4{R}:")
    for r in range(R):
        w(f"\tVLD1.P 16({rowa[r]}), [V{av(r)}.S4]")
    for j in range(4):
        w(f"\tVLD1 (R2), [V20.S4, V21.S4, V22.S4, V23.S4]")
        w("\tADD R5, R2, R2")
        for r in range(R):
            for c in range(4):
                w(f"\tWORD ${fmla_elem(acc(r,c), bv(c), av(r), j):#08x} // FMLA V{acc(r,c)}.4S, V{bv(c)}.4S, V{av(r)}.S[{j}]")
    w("\tSUB $4, R6, R6")
    w("\tCMP $4, R6")
    w(f"\tBGE loop4{R}")
    w(f"tail{R}:")
    w(f"\tCBZ R6, store{R}")
    w(f"tail1{R}:")
    for r in range(R):
        # load one float into lane 0 (FMOVS zeroes the rest; lane 0 is all FMLA reads)
        w(f"\tFMOVS.P 4({rowa[r]}), F{av(r)}")
    w(f"\tVLD1 (R2), [V20.S4, V21.S4, V22.S4, V23.S4]")
    w("\tADD R5, R2, R2")
    for r in range(R):
        for c in range(4):
            w(f"\tWORD ${fmla_elem(acc(r,c), bv(c), av(r), 0):#08x} // FMLA V{acc(r,c)}.4S, V{bv(c)}.4S, V{av(r)}.S[0]")
    w("\tSUBS $1, R6, R6")
    w(f"\tBNE tail1{R}")
    w(f"store{R}:")
    for r in range(R):
        w(f"\tVST1 [V{acc(r,0)}.S4, V{acc(r,1)}.S4, V{acc(r,2)}.S4, V{acc(r,3)}.S4], ({rowo[r]})")
    w("\tRET")
    w("")
sys.stdout.write("\n".join(out) + "\n")
